export default {
    CITY_FILTER_CHANGE: 'SET_CITY_TEXT_FILTER',
    CITY_FILTER_SUBMIT: 'CITY_FILTER_SUBMIT',
    CITY_FILTER_CLEAR: 'CITY_FILTER_CLEAR',
    CITY_SELECTOR_PICK: 'CITY_SELECTOR_PICK'
}